// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {plan} from '../models';
import {main} from '../models';
import {cloudsync} from '../models';

export function ConnectGoogleDrive():Promise<void>;

export function ConnectS3(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CreateRace(arg1:plan.Race):Promise<plan.Race>;

export function DeletePinnedInsight(arg1:number):Promise<void>;

export function DeleteRace(arg1:string):Promise<void>;

export function DisconnectCloud():Promise<void>;

export function DisconnectStrava():Promise<void>;

export function ExportChatSessions():Promise<Array<number>>;

export function ExportContext(arg1:string):Promise<void>;

export function GeneratePlan(arg1:string):Promise<plan.TrainingPlan>;

export function GetActivePlan():Promise<plan.TrainingPlan>;

export function GetActivityStats():Promise<main.StatsData>;

export function GetContextPreview():Promise<string>;

export function GetOllamaModels(arg1:string):Promise<Array<string>>;

export function GetPinnedInsights():Promise<Array<main.InsightData>>;

export function GetPlanWeeks(arg1:string):Promise<Array<plan.Week>>;

export function GetProfileData():Promise<main.ProfileData>;

export function GetRecentActivities(arg1:number):Promise<Array<main.ActivityRecord>>;

export function GetSettingsData():Promise<main.SettingsData>;

export function GetStravaAuthStatus():Promise<Record<string, any>>;

export function GetStravaCredentialsAvailable():Promise<boolean>;

export function GetSyncStatus():Promise<cloudsync.SyncStatus>;

export function ImportChatSessions(arg1:Array<number>,arg2:boolean):Promise<void>;

export function ImportContext(arg1:string,arg2:boolean):Promise<void>;

export function ImportFITFile(arg1:string):Promise<void>;

export function IsFirstRun():Promise<boolean>;

export function ListRaces():Promise<Array<plan.Race>>;

export function ResetApp():Promise<void>;

export function SaveInsight(arg1:string):Promise<void>;

export function SaveProfileData(arg1:main.ProfileData):Promise<void>;

export function SaveSettingsData(arg1:main.SettingsData):Promise<void>;

export function SendMessage(arg1:string):Promise<string>;

export function SetActiveRace(arg1:string):Promise<void>;

export function StartStravaAuth():Promise<void>;

export function SyncNow():Promise<void>;

export function SyncStravaActivities():Promise<void>;

export function UpdateRace(arg1:plan.Race):Promise<void>;

export function UpdateSessionStatus(arg1:string,arg2:plan.SessionStatus,arg3:plan.ActualMetrics):Promise<void>;
