// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePinnedInsight(arg1) {
  return window['go']['main']['App']['DeletePinnedInsight'](arg1);
}

export function DisconnectStrava() {
  return window['go']['main']['App']['DisconnectStrava']();
}

export function GetContextPreview() {
  return window['go']['main']['App']['GetContextPreview']();
}

export function GetOllamaModels(arg1) {
  return window['go']['main']['App']['GetOllamaModels'](arg1);
}

export function GetPinnedInsights() {
  return window['go']['main']['App']['GetPinnedInsights']();
}

export function GetProfileData() {
  return window['go']['main']['App']['GetProfileData']();
}

export function GetRecentActivities(arg1) {
  return window['go']['main']['App']['GetRecentActivities'](arg1);
}

export function GetSettingsData() {
  return window['go']['main']['App']['GetSettingsData']();
}

export function GetStravaAuthStatus() {
  return window['go']['main']['App']['GetStravaAuthStatus']();
}

export function ImportFITFile(arg1) {
  return window['go']['main']['App']['ImportFITFile'](arg1);
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function SaveInsight(arg1) {
  return window['go']['main']['App']['SaveInsight'](arg1);
}

export function SaveProfileData(arg1) {
  return window['go']['main']['App']['SaveProfileData'](arg1);
}

export function SaveSettingsData(arg1) {
  return window['go']['main']['App']['SaveSettingsData'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function StartStravaAuth() {
  return window['go']['main']['App']['StartStravaAuth']();
}

export function SyncStravaActivities() {
  return window['go']['main']['App']['SyncStravaActivities']();
}
