// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DisconnectStrava() {
  return window['go']['main']['App']['DisconnectStrava']();
}

export function GetRecentActivities(arg1) {
  return window['go']['main']['App']['GetRecentActivities'](arg1);
}

export function GetSettingsData() {
  return window['go']['main']['App']['GetSettingsData']();
}

export function GetStravaAuthStatus() {
  return window['go']['main']['App']['GetStravaAuthStatus']();
}

export function ImportFITFile(arg1) {
  return window['go']['main']['App']['ImportFITFile'](arg1);
}

export function IsFirstRun() {
  return window['go']['main']['App']['IsFirstRun']();
}

export function SaveInsight(arg1) {
  return window['go']['main']['App']['SaveInsight'](arg1);
}

export function SaveSettingsData(arg1) {
  return window['go']['main']['App']['SaveSettingsData'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function StartStravaAuth() {
  return window['go']['main']['App']['StartStravaAuth']();
}
