// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetRecentActivities(arg1:number):Promise<Array<main.ActivityRecord>>;

export function ImportFITFile(arg1:string):Promise<void>;

export function SaveInsight(arg1:string):Promise<void>;

export function SendMessage(arg1:string):Promise<string>;
