// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeletePinnedInsight(arg1:number):Promise<void>;

export function DisconnectStrava():Promise<void>;

export function GetActivityStats():Promise<main.StatsData>;

export function GetContextPreview():Promise<string>;

export function GetOllamaModels(arg1:string):Promise<Array<string>>;

export function GetPinnedInsights():Promise<Array<main.InsightData>>;

export function GetProfileData():Promise<main.ProfileData>;

export function GetRecentActivities(arg1:number):Promise<Array<main.ActivityRecord>>;

export function GetSettingsData():Promise<main.SettingsData>;

export function GetStravaAuthStatus():Promise<Record<string, any>>;

export function ImportFITFile(arg1:string):Promise<void>;

export function IsFirstRun():Promise<boolean>;

export function SaveInsight(arg1:string):Promise<void>;

export function SaveProfileData(arg1:main.ProfileData):Promise<void>;

export function SaveSettingsData(arg1:main.SettingsData):Promise<void>;

export function SendMessage(arg1:string):Promise<string>;

export function StartStravaAuth():Promise<void>;

export function SyncStravaActivities():Promise<void>;
